### ISSUE TITLE
Way to donate to project?

### ISSUE THREAD

**Issue by CorneliusCornbread** [ardaku/alloy#241]
Hey, I just wanted to ask if there is a way to donate to the development of this project. I love this image viewer and I'm so happy with its continued development, I figured I should really chip in some money to keep it going. Is there any official way to do so? Thanks!

**Comment by AldaronLau** [comment]
@CorneliusCornbread Thanks for opening this issue!  There is not currently an official way to donate, although it may be something I should look into.

I just need to figure out how to best make sure the money helps the project along, and maybe look into GitHub Sponsors.

I think monetary donations could help a project in these ways:

 - Bounties - encourage outside contributions with small monetary rewards, requires some maintenance planning
 - Day's wage - idea is can take days off work to devote to project once enough money is saved up from dontations, doesn't apply super well for me, given a salary position, but could be allocated to someone else
 - Requested features - I allocate my free time to develop a specific feature requested from a sponsor

I still need to come up with a more concrete roadmap for the project, and do better planning as a maintainer, I think for any of these.  But, also a donation could be reserved for any of these things later.  I'm curious if you have any preferences as a potential sponsor for any or multiple of those options, or something else entirely?

**Comment by CorneliusCornbread** [comment]
@AldaronLau I don't have much of a preference, though having both the option for a regular donation and a one time donation would be really nice.

I figured I should show that there's interest in the continued development of this project and the best way to do that is a donation.

_Though I will admit I'm just a broke college kid so the best I can do is buy you lunch lol_

**Comment by AldaronLau** [comment]
@CorneliusCornbread Thanks for the feedback.  I'll look into setting something up - may take me a bit, though.

**Comment by AldaronLau** [comment]
@CorneliusCornbread I just set up GitHub Sponsors, with default settings.  The sponsor button should show up in the right column with one-time and recurring donation options.  Thanks!
